# Generated by Django 4.1 on 2022-09-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_watched', models.TextField()),
                ('film_tittle', models.TextField()),
                ('film_rating', models.TextField()),
                ('film_release_date', models.TextField()),
                ('film_review', models.TextField()),
            ],
        ),
    ]
